### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Rizhiy** [leath-dub/snipe.nvim#1]
Setup with lazy, but nothing shows up.

Also, the naming convention doesn't seem to match typical. Lazy usually uses `config`, rather than `setup`.

**Comment by yujinyuz** [comment]
doesn't work for me as well

**Comment by leath-dub** [comment]
Yeah sorry I don't use lazy, I am changing it to `config` over `setup`

**Comment by leath-dub** [comment]
> doesn't work for me as well.
> 
> tried the mapping and also manually running `:lua require('snipe').toggle_buffer_menu()` but nothing happens

This actually doesnt open the menu it returns a function that when called will open the menu

**Comment by leath-dub** [comment]
I think I am gonna rename that function as it is a bit misleading.

**Comment by yujinyuz** [comment]
@leath-dub okay that makes sense..

It works now but why did you do it this way rather than just `toggle_buffer_menu()` ?

**Comment by leath-dub** [comment]
It is consistent with menu creation in general. A menu keeps its state in a closure so you need to call a function that returns the closure. I can change it for `toggle_buffer_menu` specifically if that helps ?

**Comment by leath-dub** [comment]
I will close this issue any way, I just pushed the fix

**Comment by yujinyuz** [comment]
alright. But if users would want to utilize the `keys` for using lazy.nvim they would have to define it like this

```lua
  {
    'leath-dub/snipe.nvim',
    keys = {
      {
        'gb',
        function()
          require('snipe').toggle_buffer_menu()()
        end,
      },
    },
    config = function()
      local snipe = require('snipe')
      snipe.setup()
    end,
  },
```

which it just doesn't feel quite right compared to 
```lua
  {
    'leath-dub/snipe.nvim',
    keys = {
      {
        'gb',
        function()
          require('snipe').toggle_buffer_menu()
        end,
      },
    },
    config = function()
      local snipe = require('snipe')
      snipe.setup()
    end,
  },
```

**Comment by leath-dub** [comment]
> alright. But if users would want to utilize the `keys` for using lazy.nvim they would have to define it like this
> 
> ```lua
>   {
>     'leath-dub/snipe.nvim',
>     keys = {
>       {
>         'gb',
>         function()
>           require('snipe').toggle_buffer_menu()()
>         end,
>       },
>     },
>     config = function()
>       local snipe = require('snipe')
>       snipe.setup()
>     end,
>   },
> ```
> 
> which it just doesn't feel quite right compared to
> 
> ```lua
>   {
>     'leath-dub/snipe.nvim',
>     keys = {
>       {
>         'gb',
>         function()
>           require('snipe').toggle_buffer_menu()
>         end,
>       },
>     },
>     config = function()
>       local snipe = require('snipe')
>       snipe.setup()
>     end,
>   },
> ```

well it would maybe look better as `{ "gb", require("snipe").toggle_buffer_menu() }`

**Comment by yujinyuz** [comment]
That won't work because it executes `require('snipe')` before the plugin is loaded.
They will get this error

```
Error detected while processing /Users/traf/.config/nvim/init.lua:
Failed to load `my.plugins.experiments`

/Users/traf/.config/nvim/lua/my/plugins/experiments.lua:7: module 'snipe' not found:
^Ino field package.preload['snipe']
cache_loader: module snipe not found
cache_loader_lib: module snipe not found
```

**Comment by leath-dub** [comment]
> That won't work because it executes `require('snipe')` before the plugin is loaded. They will get this error
> 
> ```
> Error detected while processing /Users/traf/.config/nvim/init.lua:
> Failed to load `my.plugins.experiments`
> 
> /Users/traf/.config/nvim/lua/my/plugins/experiments.lua:7: module 'snipe' not found:
> ^Ino field package.preload['snipe']
> cache_loader: module snipe not found
> cache_loader_lib: module snipe not found
> ```

Ohh right fair enough, I don't think its a big deal though for now Ill add a note about it in the readme ( I don't want to break anyones configs if they already are using this )

**Comment by Rizhiy** [comment]
>  ( I don't want to break anyones configs if they already are using this )

This project is literally 19 hours old, renaming the function now to avoid further confusion is an obvious thing to do.
It should be something along the lines of `create_buffer_men()` instead, if it only creates it without opening it.
"toggle" implies that something will open or close, so this is very confusing.

**Comment by leath-dub** [comment]
> > ( I don't want to break anyones configs if they already are using this )
> 
> This project is literally 19 hours old, renaming the function now to avoid further confusion is an obvious thing to do. It should be something along the lines of `get_function_to_toggle_menu()` instead, if it only creates the function without calling it. "toggle" implies that something will open or close, so this is very confusing.

how about `create_toggle_buffer_menu` is that less confusing ?

**Comment by Rizhiy** [comment]
The function needs to describe what it does. `create_toggle_buffer_menu` sounds like it would create a menu object which I would then pass into another function to display it. Given that many words in English can be both verbs and nouns, it is better to be more precise.
You are returning a function (callable) which toggles a buffer menu, so the function name should indicate that.
To me, either `create_function_to_toggle_menu` or `create_buffer_menu_toggler` makes more sense.

**Comment by leath-dub** [comment]
> The function name needs to describe what it does. `create_toggle_buffer_menu` sounds like it would create a menu object, which can be toggled and contains buffers. Given that many words in English can be both verbs and nouns, it is better to be more precise. As far as I understand, you are returning a function (callable) which toggles a buffer menu, so the function name should indicate that. To me, either `create_function_to_toggle_buffer_menu` or `create_buffer_menu_toggler` makes more sense.

Yeah I think your right, forgive I am a bit partial to functional style so I think of closures as objects (they pretty much are), but I understand that it is confusing, thanks for the feedback, ill fix this now.
