### ISSUE TITLE
Modal buffer actions

### ISSUE THREAD

**Issue by dwoznicki** [leath-dub/snipe.nvim#14]
I really like this plugin! I've actually been working on something similar since I saw [this reddit post](https://www.reddit.com/r/neovim/comments/1e3gsyb/indexbased_buffers_navigation/).

### Concept

One thing I noticed as I used the simple version of my plugin is that I wanted to perform different actions on my buffers, and I wanted to use my hint keys to do so. Usually I just wanted to open the buffer, occasionally delete it, and just a few times I wanted to open the buffer in a `vsplit`. The direction I was leaning in to solve this was to incorporate modal buffer actions.

The idea is fairly simple. Selecting a buffer (either by its hint tag or by scrolling to it and hitting enter) will do something different based on the current mode. By default, the list is in `Open` mode. Pressing `D` changes to `Delete` mode, where selecting a buffer deletes it. And so on.

My idea was to put the current mode in the title bar

```
╭Snipe [Open]─────────╮
```

but you could also change the tag color, put it somewhere more obviously visible, etc.

### Caveats

This functionality overlaps with #13, which is a more standard way to add support for additional actions. I think modes are more powerful, but they're also harder to reason about. Modes would also increases the complexity of this tool a fair bit, which may not be the direction you want to go in.

If you are interested, I'd be happy to contribute the feature.

**Comment by linkarzu** [comment]
- Interesting way of thinking about it. 
- With the traditional way I'm suggesting you just position yourself in the buffer, press a single key and the buffer is gone, it leaves you back in snipe so you can press the key again, I like having mine set to "d" because it's easier to press than "D". 
  - Even though some people may close stuff by accident by using "d" I'm used to it from BufExplorer, and was thinking of adding a "u" keymap to "undo" or something (but "D" would solve this small problem for most people)
- Based on what I understand, with what you're proposing, I would have to press "D" to enter the mode, and then I have to hit enter to delete the buffer or is it another key to delete it?
  - Then when in the mode I can press <esc> or <q> whichever I prefer to quit entirely of snipe or I have to go back to the normal mode to quit?

**Comment by leath-dub** [comment]
This is an interesting idea. I think the current plan for snipe is the expose more user events. I even think that this feature may be already possible with the `SnipeCreateBuffer` event, it could when triggered setup some keybinds in the buffer to switch modes and modify some state for the callback to use to determine the action to perform when an item is selected.

**Comment by linkarzu** [comment]
> This is an interesting idea. I think the current plan for snipe is the expose more user events. I even think that this feature may be already possible with the `SnipeCreateBuffer` event, it could when triggered setup some keybinds in the buffer to switch modes and modify some state for the callback to use to determine the action to perform when an item is selected.

@leath-dub does this mean I can implement my "D" keymap somewhere to close a buffer without you modifying your plugin? I'd be happy to do that

**Comment by leath-dub** [comment]
> > This is an interesting idea. I think the current plan for snipe is the expose more user events. I even think that this feature may be already possible with the `SnipeCreateBuffer` event, it could when triggered setup some keybinds in the buffer to switch modes and modify some state for the callback to use to determine the action to perform when an item is selected.
> 
> @leath-dub does this mean I can implement my "D" keymap somewhere to close a buffer without you modifying your plugin? I'd be happy to do that

Yeah well thats the idea, I don't mind merging helpers for this kind of thing but I would rather the core be extensible enough to support this kind of functionality without needing to modify the source itself.

**Comment by linkarzu** [comment]
- Makes sense now @dwoznicki, thanks for explaining. 
- It seems I could get used to the functionality you're suggesting, I'd have to be more careful and look at my keyboard before pressing the letter of the buffer I want to close though, I can always re-open it of course but I think I'll be closing unwanted buffers (I know, skill issue)
- What if we have 2 modes? The `modal buffer actions` mode and `standard` mode and you chose how you want the plugin to operate?
  - Repo owner: "This ain't no freaking ice cream to choose and pick your stuff" 🤣

**Comment by leath-dub** [comment]
With the rewrite (actually started now) this should be easy enough as the "snipe menu" will just a be state object with a configuration. For compatibility I will keep the old config style, as much as I want to remove it :), but essentially there will be a "default" menu that acts on that configuration. Users can create their own menus and you can modify the configuration in place between calls to `open` such that you can change the title but also pass a different callback for how to handle the selected item.

**Comment by leath-dub** [comment]
In fact I think Ill create an example in the repo when I am finished

**Comment by leath-dub** [comment]
I added an example in the readme on the `snipe2` branch, let me know if that is what you had in mind.

**Comment by leath-dub** [comment]
Going to close this for now as it is really easy to implement with `snipe2`, feel free to reopen if you disagree.
