### ISSUE TITLE
Open Buffer Command Opens Two Snipe Buffers

### ISSUE THREAD

**Issue by gordoncyu** [leath-dub/snipe.nvim#17]
In db1b2af "fix indent" you didn't remove the original bad indent line resulting in two calls to opening the buffer. This completely breaks functionality as it will open the target buffer in the other snipe buffer once you select one.

```lua
vim.keymap.set({'n', 'x'}, 'go', function () 
    require("snipe").open_buffer_menu()
    vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<C-w>q', true, false, true), 'n', false)
end)
```

As a temp fix for anyone else having this problem.

**Comment by leath-dub** [comment]
ohh shit, that is embarrassing. Could someone open a pr Ill merge it. Not at my pc for a while.

**Comment by leath-dub** [comment]
tiny fix just did it on my phone :)
