### ISSUE TITLE
Show relative paths for buffers within `:pwd`

### ISSUE THREAD

**Issue by farnoy** [leath-dub/snipe.nvim#18]
Great plugin, thanks for publishing it!

I think a reasonable default, or maybe an option, would be to show paths as relative to `:pwd` if they're under the directory that nvim is opened in. And then show absolute paths for everything not descending from it.

**Comment by leath-dub** [comment]
thats fair actually ill add that once i get back

**Comment by farnoy** [comment]
This didn't fix every case, unfortunately. On Linux, I still have some buffers that are opened through `~/user/...path` and that doesn't get simplified properly with my change.

Any ideas as to what else is needed?

**Comment by leath-dub** [comment]
> This didn't fix every case, unfortunately. On Linux, I still have some buffers that are opened through `~/user/...path` and that doesn't get simplified properly with my change.
> 
> Any ideas as to what else is needed?

Try `snipe2` branch, it uses the output of `ls` which already shortens path names. I don't have any issue with the way it functions as of now, so I don't plan to implement this myself. If you do implement it: maybe as a alternate format function, I will happily merge it into the new `contrib.lua` file.
