### ISSUE TITLE
[Bug] Buffer list is incomplete

### ISSUE THREAD

**Issue by Rizhiy** [leath-dub/snipe.nvim#2]
Buffer list in sniper doesn't match what is provided by `:buffers`.
Generally, buffer pickers use that list (e.g. `:Telescope buffers`).

Not sure what the problem is, probably has something to do with that I'm loading a session.

**Comment by samuellawerentz** [comment]
Faced this issue where telescope buffers and snipe buffers list were not matching.  I use `auto-session` to load my nvim session.

**Comment by leath-dub** [comment]
I just pushed some changes there would someone mind seeing if that fixes the issue for your sessionizers

**Comment by samuellawerentz** [comment]
Yep, seems to work fine with `auto-sessions` .

Thanks!

**Comment by leath-dub** [comment]
Good to hear !

**Comment by Rizhiy** [comment]
Works now
