### ISSUE TITLE
Idea: Group by directory, add tree view

### ISSUE THREAD

**Issue by ognjen-vuceljic** [leath-dub/snipe.nvim#20]
Hi,

awesome plugin, thanks a lot for working on this!

This is an idea coming from someone that works on Salesforce projects, with so many different directories and subdirectories within a project:

- it would be good if Snipe window can show tree-like view, with options grouped by their parent directory

Please find the example below:

**Current state**

![Screenshot 2024-08-05 at 23 32 08](https://github.com/user-attachments/assets/1a8c0aac-da75-444f-9d80-0fa830639942)

**Potential future state**

![image](https://github.com/user-attachments/assets/4a4d80a8-75c2-4b21-898c-d3b5cf5b78f6)

I hope I was able to outline the idea properly!

Thank you very much.

**Comment by leath-dub** [comment]
not really willing to maintain this kind of feature itself although I will maybe try to make the api more flexible such that you can create your own uis with the selection logic abstracted away.
