### ISSUE TITLE
Feature request: show active buffer on the list

### ISSUE THREAD

**Issue by jellydn** [leath-dub/snipe.nvim#21]
# What

Show active buffer on the list and it shouldn't be selectable

# How

Currently, our buffer list looks like this:

[![Image from Gyazo](https://i.gyazo.com/de82547f5a7550820311159d32f1b391.png)](https://gyazo.com/de82547f5a7550820311159d32f1b391)

I found the way fzf-lua does with `FzfLua buffers` is more user-friendly. Please take a look at the screenshot below. Could we implement something similar?

[![Image from Gyazo](https://i.gyazo.com/cc271a89789a39989b98028b2c043583.png)](https://gyazo.com/cc271a89789a39989b98028b2c043583)

Looking forward to your thoughts on this request. Thank you!

**Comment by leath-dub** [comment]
ahh right so have the cursor default on the current buffer?

**Comment by jellydn** [comment]
> ahh right so have the cursor default on the current buffer?

Correct 👍

**Comment by leath-dub** [comment]
Ok so this will be possible in the new version. When opening a menu you can pass an optional "preselect" argument which will jump you the item at that preselected index

**Comment by leath-dub** [comment]
This is now possible vi `ui.preselect_current` option on the `snipe2` branch
