### ISSUE TITLE
Feature Request: buffer numbers for first 10 on list, then single letters, then two

### ISSUE THREAD

**Issue by jam1015** [leath-dub/snipe.nvim#22]
Two related requests:
1) Have the option for the keys to get to a buffer just be the numbers 1-9 for the first 9 buffers, and then rely on letter combinations for the others

2) For those letter combinations, present as many one letter codes as possible, and then jump to two letter codes when necessary . Right now it only presents two letter codes when the number of buffers exceeds the number of characters in the hints dictionary

**Comment by leath-dub** [comment]
> Have the option for the keys to get to a buffer just be the numbers 1-9 for the first 9 buffers, and then rely on letter combinations for the others

Do you mean have each number associate with the buffers id/nr or just that the first 9 presented. If the latter this is already possible if you just prefix the dictionary with "123456789..."

> For those letter combinations, present as many one letter codes as possible, and then jump to two letter codes when necessary . Right now it only presents two letter codes when the number of buffers exceeds the number of characters in the hints dictionary

This is definitely something I want to look into, I am going to refer to some other plugins to see how they generate the key tags ( maybe mini.jump and mini.jump2d will help me here ).

**Comment by jam1015** [comment]
> Do you mean have each number associate with the buffers id/nr or just that the first 9 presented. If the latter this is already possible if you just prefix the dictionary with "123456789..."

The first thing.  For the first ten buffers, or perhaps more, access the buffers with their actual numbers. Use '0' for buffer 10.





> This is definitely something I want to look into, I am going to refer to some other plugins to see how they generate the key tags ( maybe mini.jump and mini.jump2d will help me here ).

Thanks for making such a great plugin, I wanted to make something like this but getting it done would have been very difficult and time consuming for me, or a mess of autocommands in vimscript.

**Comment by leath-dub** [comment]
I don't think there is a good way to implement this, the problem with having one as many one letter tags as possible is you have to partition the dictionary into however many tag lengths you expect to have, as you cant have shared prefixes.
