### ISSUE TITLE
Feature request: Only shot last x used buffers

### ISSUE THREAD

**Issue by oysandvik94** [leath-dub/snipe.nvim#24]
I dont really close buffers, so I can end up with a huge list.

I usually use a global mark for buffers I want to navigate to frequently, so this plugin is useful for me when I want to navigate to a buffer that I had recently accessed but not tagged. So for that reason it would be nice if I was able to limit the menu to only show the top x last used buffers, specified in the config. 

If this is a feature that is aligned with your goals of the plugin I would love to create a PR!

**Comment by leath-dub** [comment]
I plan to refactor most of the code currently so this is why I am avoiding adding much features into the core right now ( I will have to maintain them then ). I am quite busy right now so I haven't had the time. What would be really helpful as a PR is to add a `contrib/` submodule so like `lua/snipe/contrib/` where we can put different producers people write.

**Comment by oysandvik94** [comment]
Understandable! I can maybe take a look at some point.

**Comment by leath-dub** [comment]
I think this will be possible in the new version just through the configuration. You can set the "max_height" to "x" (last x buffers) and change `sort` to be "last".

**Comment by leath-dub** [comment]
I think you can use the following config to only show the last 10 buffers by usage:

```lua
{ ui = { max_height = 10 }, sort = "last" }
```
