### ISSUE TITLE
Feature Request: Add an option to change border (Eg. single, rounded etc.)

### ISSUE THREAD

**Issue by DanWlker** [leath-dub/snipe.nvim#29]
Hi, is it possible to expose the configuration for border (single, rounded, double etc.) to the user? I can whip up a PR if you're not free for it. Maybe some padding as well? Thank you

**Comment by leath-dub** [comment]
You can now override the configuration passed to `nvim_open_win`. So for example in the configuration you can now do:

```lua
{
  ...
  ui = { open_win_override = { border = "rounded" } }
  ...
}
```

See `:h nvim_open_win` for more info
