### ISSUE TITLE
[Feature Request] Options for where to draw selection menu

### ISSUE THREAD

**Issue by Rizhiy** [leath-dub/snipe.nvim#3]
I have a pretty big monitor, and generally looking at the top left is not very quick.
Ideally, there should be at least two more options:
* `center` or `middle` or something similar - draw window in the centre similar to telescope and floating terminals.
* `cursor` - draw the menu at the cursor (my preference) since this is already where I'm looking at. Similar to https://github.com/tversteeg/registers.nvim

**Comment by leath-dub** [comment]
I just pushed some changes there that allow this:

```lua
...
  ui = {
    max_width = -1, -- -1 means dynamic width
    -- Where to place the ui window
    -- Can be any of "topleft", "bottomleft", "topright", "bottomright", "center", "cursor" (sets under the current cursor pos)
    position = "topleft",
  },
...
```

**Comment by Rizhiy** [comment]
It works
