### ISSUE TITLE
bug: snipe buffer opening file contents inside itself

### ISSUE THREAD

**Issue by FxmousKid** [leath-dub/snipe.nvim#33]
Hello, first of all thank you for that extension, but i've encountered a bug where if you press you're shortcut for 
```require("snipe").open_buffer_menu()``` , which opens the menu to choose a buffer, as intended, and then you press that same shortcut again, it makes the tiny snipe menu buffer open one of the files :

https://github.com/user-attachments/assets/5b0a654c-f8fb-4311-a424-5a10e1f8a688

sorry for no display of keystrokes... if anyone isn't able to repoduce, i'll detail the issue more. thank you !

**Comment by leath-dub** [comment]
This is already fixed in the rewrite (just tested), I am going to try to have the rewrite in a separate branch by the end of today ("snipe2"). Still have to decide where best to notify people about this though :>

**Comment by FxmousKid** [comment]
Hey, imo since the issue is not that big of a bug, and if I understood correctly you're rewriting the whole thing ? If that's the case,  might as well wait to finish ? (I've been using snipe for a few weeks, didn't even notice that until the date of writing)

Thanks for you work man !

**Comment by leath-dub** [comment]
> Hey, imo since the issue is not that big of a bug, and if I understood correctly you're rewriting the whole thing ? If that's the case, might as well wait to finish ? (I've been using snipe for a few weeks, didn't even notice that until the date of writing)
> 
> Thanks for you work man !

Rewrite is done, you can change to the new branch `snipe2`, I am pretty sure this issue is not a problem with the new version. Would you mind checking ?

**Comment by FxmousKid** [comment]
Absolutely perfect, thank you so much, work as intended now ! i'll now be closing the issue

**Comment by FxmousKid** [comment]
Hey, i just re-experienced the bug.

1) Open a file in nvim
2) open snipe buffer (even if only 1 buffer opened)
3) open Telescope file searcher buffer perhaps (or other interactive file picker
4) file will open in the snipe buffer...

I think this issue is not only for Telescope but generally that once i open the snipe buffer, all actions become centered there, including file choosing and whatnot, i dont know if this can be fixed from the scope of the plugin :thinking: 

footage : 

https://github.com/user-attachments/assets/7e11c59e-1dbb-40fd-86ef-d1a993e034b5

**Comment by leath-dub** [comment]
> Hey, i just re-experienced the bug.
> 
>     1. Open a file in nvim
> 
>     2. open snipe buffer (even if only 1 buffer opened)
> 
>     3. open Telescope file searcher buffer perhaps (or other interactive file picker
> 
>     4. file will open in the snipe buffer...
> 
> 
> I think this issue is not only for Telescope but generally that once i open the snipe buffer, all actions become centered there, including file choosing and whatnot, i dont know if this can be fixed from the scope of the plugin 🤔
> 
> footage :
> Screencast.from.2024-11-17.03-39-27.mp4

Not really sure how I can fix this as essentially telescope is just opening the buffer in the snipe window because that is the currently focused window. If anything I think this is something that would need to be handled in telescope, not sure though.

**Comment by leath-dub** [comment]
Unless somebody has a fix, which I don't think there is one, I am going to close this for now.
