### ISSUE TITLE
Feature Request: Option to manually set tag

### ISSUE THREAD

**Issue by justyn** [leath-dub/snipe.nvim#37]
It would be useful to have the option to manually set the tag, by selecting the entry, hitting a key and then entering the desired tag for the entry.

This would be very handy for quickly setting tags to something that is easier to remember.

This feature request presupposes that tags stay fixed (except perhaps when necessary for multi-character tags) as per https://github.com/leath-dub/snipe.nvim/issues/16#issuecomment-2451811895

Thanks for the great work on this plugin!

**Comment by leath-dub** [comment]
Hmm this is interesting I will look into how the `lsp.buf.rename` function prompts user.

**Comment by leath-dub** [comment]
seems like it uses vim.ui.input()

**Comment by leath-dub** [comment]
Added to the snipe2 branch. You can now use the default bind "C" to change the tag manually.

**Comment by leath-dub** [comment]
> [@leath-dub](https://github.com/leath-dub) when setting a tag manually it does not unmap currently existing tags, leading to a bug where multiple buffers have the same tag but only one of them is accessible. For example here all buffers are mapped to `a` but only the last one is accessible: ![Image](https://github.com/user-attachments/assets/63f39393-aade-47cd-9e2a-7c3ebe7cdb35)
> 
> Ideally when I set a manual tag I'd expect the plugin to check if it's already assigned, if it is - untag the old buffer and put a new available tag to it from the dictionary.

I have some what of a plan for this. I have just got the "persist tags" feature working (not pushed yet). I think I will make it so that manually setting tags is only allowed if that feature is enabled. This is so that it can be pretty trivial to transfer a tag from a buffer and give another a buffer another tag instead.

**Comment by leath-dub** [comment]
I had a stab at this feature with the new persistent tags. I don't think it is worth the cost of maintaining it for me. There are so many edge cases and I worry that if I implement this, it will likely have some quirks that I did not consider. I would rather not support a feature that I don't want to maintain.

Sorry if this is something you really want. I will keep the old tested way that is not perfect, but it won't work with the new "persist tags" feature.
