### ISSUE TITLE
Add option to center menu relative to terminal width rather than root window width

### ISSUE THREAD

**Issue by edlandm** [leath-dub/snipe.nvim#39]
I like my snipe window to show up in the absolute center of my terminal window, and that is what I would expect setting its position to 'center' to do.
Snipe appears to be determining the max width for centering by checking the width of the first window in the tabpage, which means that vertical splits interfere with it, for example:
![msrdc_IGJ4pouGaa](https://github.com/user-attachments/assets/90be0f30-1a3b-4ad9-b811-6ea5537f3ef6)

Making the following change in Menu:get_window_opts centers the snipe window in the way that I would expect/like:
![image](https://github.com/user-attachments/assets/c2076a75-882d-494f-8944-20e71ec6be60)

![msrdc_Pluueb9ssY](https://github.com/user-attachments/assets/70a90fae-77d0-4f4b-bece-e7ded0e608bd)

I created this issue rather than a pull request because I wasn't sure if you intended 'center' to behave like in my first screenshot, in which case I think this should be an additional position type, so I thought I should leave the implementation decision to you. Let me know if you need any more information. Cheers!

**Comment by nvktools** [comment]
+1 I think at the very least this should open it in the center of the active split instead of the first one. Another setting for center of the window would be nice too

**Comment by leath-dub** [comment]
This is a very good catch ! I didn't really know that you could use `vim.opt.columns` so I did that tabpage thing to get the "root" window as you say. Thanks for pointing this out, Ill fix this when I get a chance !
