### ISSUE TITLE
ui.position = "cursor" jumps around screen when closing buffers

### ISSUE THREAD

**Issue by nickvonkaenel** [leath-dub/snipe.nvim#40]
Noticing that the window jumps around a lot with any action that keeps the window open because it opens with the new cursor position. For actions like that it would make sense for the window to stay in the current position

**Comment by leath-dub** [comment]
I am having trouble understanding when this happens ? could you give an example so I can try to reproduce it ?

**Comment by nickvonkaenel** [comment]
https://github.com/user-attachments/assets/af340c36-cc2b-4478-a3e9-af523fa04200

Sorry, looking back my explanation was not that great. Here is a video showing what happens when you are using the 'cursor' position and you delete buffers from the list.

**Comment by leath-dub** [comment]
> WezTerm.2024-11-09.07.38.13.mp4
> 
> Sorry, looking back my explanation was not that great. Here is a video showing what happens when you are using the 'cursor' position and you delete buffers from the list.

Ohh that is definitely not right, I see the issue now !

**Comment by leath-dub** [comment]
Hopefully this solves it, from my brief testing it seems to do the trick

**Comment by leath-dub** [comment]
Thanks for pointing this out!
