### ISSUE TITLE
Feature request: ability to put tags to right of buffer names

### ISSUE THREAD

**Issue by justyn** [leath-dub/snipe.nvim#41]
A nice option when using `text_align=right` would be to be able to put the tags to the right of the buffer names too.

I'm particularly thinking for any situation where the buffer names also contain the path so that right-align ensures the tag is placed close to actual filename rather than its parent directories.

If you hide parent directories then there is less need for this feature.

Apologies if this option is already possible and I missed it.

**Comment by leath-dub** [comment]
I will take a look at this when I get to fixing a couple other issues. This is a good idea!

**Comment by leath-dub** [comment]
Think more on this, a lot of the features like shortening the paths and aligning the buffers are all just for readability. I have just wrote a new feature that I think fixes most of these issues (not committed).

There will be a new option `text_align = "file-first"` which will format the buffers like so:

```
s buffer.lua  @ lua/snipe
a contrib.lua @ lua/snipe
d init.lua    @ lua/snipe
f menu.lua    @ lua/snipe
l slice.lua   @ lua/snipe
```

I would love to here what people think about this as compared to implementing all these other post processing things. Maybe this with a truncate optional to cut off the right side is a nice idea ?

**Comment by justyn** [comment]
For me personally, this would probably be a good approach!
I'd also like to add git/filesave status which would probably fit in well with this format.

**Comment by leath-dub** [comment]
> For me personally, this would probably be a good approach! I'd also like to add git/filesave status which would probably fit in well with this format.

You know I think so, I don't want that in the core though, I will see what I can expose to allow adding extra information easy. I am going to close this issue for now, unless somebody else really want this feature considering the alternative that exists now.
