### ISSUE TITLE
Closing snipe with multiple keys

### ISSUE THREAD

**Issue by victor-falcon** [leath-dub/snipe.nvim#45]
I find myself pressing either esc or q to close the modal but only one works. It's possible to set two keys for this action?

**Comment by leath-dub** [comment]
> I find myself pressing either esc or q to close the modal but only one works. It's possible to set two keys for this action?

You can see how the default menu binds it here (if you are interested):

https://github.com/leath-dub/snipe.nvim/blob/main/lua/snipe/init.lua#L168

So to add an extra keybind we just need to do the same:

```lua
require("snipe"):global_menu:add_new_buffer_callback(function(m)
  vim.keymap.set("n", "q", function() m:close() end, { nowait = true, buffer = m.buf })
end)
```

Let me know if this resolves your issue
