### ISSUE TITLE
Feature request: make config.ui.preselect_current more general

### ISSUE THREAD

**Issue by davidsierradz** [leath-dub/snipe.nvim#46]
Hi, checking #21, would be nice if we could refactor `config.ui.preselect_current` to something like `config.ui.preselect`, this option could accept from a predefined list of strings (`%`, `#` and `false` for example) so we can preselect the current (`%`) buffer, the alternate (`#`) buffer or none (`false`).

This would allow us to mimic Telescope's `telescope.builtin.buffers()` with `sort_lastused` flag (to preselect last used buffer).

```diff
@ lua/snipe/init.lua:237 @ function Snipe.open_buffer_menu()
   end
   Snipe.global_menu:add_new_buffer_callback(Snipe.default_keymaps)

-  if Snipe.config.ui.preselect_current then
+  if Snipe.config.ui.preselect then
     local opened = false
     for i, b in ipairs(Snipe.global_items) do
-      if b.classifiers:sub(2,2) == "%" then
+      if b.classifiers:sub(2,2) == Snipe.config.ui.preselect then
         Snipe.global_menu:open(Snipe.global_items, Snipe.default_select, Snipe.default_fmt, i)
         opened = true
       end
```

More generally, we could allow this to also be a function with `global_items` as an argument and return the item to preselect.

What do you think? Thanks.

**Comment by leath-dub** [comment]
> Hi, checking #21, would be nice if we could refactor `config.ui.preselect_current` to something like `config.ui.preselect`, this option could accept from a predefined list of strings (`%`, `#` and `false` for example) so we can preselect the current (`%`) buffer, the alternate (`#`) buffer or none (`false`).
> 
> This would allow us to mimic Telescope's `telescope.builtin.buffers()` with `sort_lastused` flag (to preselect last used buffer).
> 
> ```diff
> @ lua/snipe/init.lua:237 @ function Snipe.open_buffer_menu()
>    end
>    Snipe.global_menu:add_new_buffer_callback(Snipe.default_keymaps)
> 
> -  if Snipe.config.ui.preselect_current then
> +  if Snipe.config.ui.preselect then
>      local opened = false
>      for i, b in ipairs(Snipe.global_items) do
> -      if b.classifiers:sub(2,2) == "%" then
> +      if b.classifiers:sub(2,2) == Snipe.config.ui.preselect then
>          Snipe.global_menu:open(Snipe.global_items, Snipe.default_select, Snipe.default_fmt, i)
>          opened = true
>        end
> ```
> 
> More generally, we could allow this to also be a function with `global_items` as an argument and return the item to preselect.
> 
> What do you think? Thanks.

I think the function approach is better and we can have some predefined preselectors. Ill have a look this should be pretty easy to add

**Comment by leath-dub** [comment]
Let me know if this fixes your issue, There is a new option: `ui.preselect` which is a function that just takes the buffer list and returns an index, this can now be used for pre-selection. There is also a builtin helper: `require("snipe").preselect_by_classifier` which you could for example use as follows to pre-select the alternate buffer:

```lua
...
  preselect = require("snipe").preselect_by_classifier("#"),
...
```
