### ISSUE TITLE
Toggle off

### ISSUE THREAD

**Issue by alankritjoshi** [leath-dub/snipe.nvim#5]
Repeating toggle() twice doesn't toggle snipe off. Looks like the buffer gets overtaken. Maybe im using it incorrectly.

<img width="901" alt="Screenshot 2024-07-28 at 11 29 25 PM" src="https://github.com/user-attachments/assets/517f1961-fad0-48b2-9dc9-38b7faf3eb18">

**Comment by leath-dub** [comment]
Oh I think this is maybe a problem with using it in the `keys` field. I have not tested that as I don't use `lazy.nvim`. All of the state for the toggle is kept inside the function returned by `create_buffer_toggler` so it seems like case this function is invoked as the "toggle" it keeps resetting the state. For now use the other config, I am not sure if there is a solution to this though.

**Comment by leath-dub** [comment]
I have removed that portion from the readme, for now I am not going to support this kind of thing, the plugin is very small I personally lazy load it like so (I don't use lazy):

```lua
local function keymap_stub(mode, lhs, callback, opts)
  vim.keymap.set(mode, lhs, function()
    vim.keymap.del(mode, lhs)
    callback()
    vim.api.nvim_input(lhs) -- replay keybind
  end, opts)
end

keymap_stub("n", "gj", function()
  local snipe = require("snipe")
  snipe.setup()
  vim.keymap.set("n", "gj", snipe.create_buffer_menu_toggler({ max_path_width = 3 }))
end)
```
