### ISSUE TITLE
[Bug]: Notification of conflicting options for ui.preselect

### ISSUE THREAD

**Issue by andysazima** [leath-dub/snipe.nvim#54]
Whenever I open nvim, I get a notification:

> "(snipe) Conflicting options: ui.preselect_current is set to false while ui.preselect is not nil"

This is due to what I think is a mistaken boolean in `init.lua`.

```lua
-- Make sure they are not using preselect_current and preselect
if config.ui.preselect == nil and config.ui.preselect_current ~= false then
    vim.notify("(snipe) Conflicting options: ui.preselect_current is set to false while ui.preselect is not nil")
end
```

The notification specifically says "ui.preselect is not nil", but the `if` statement is checking for `config.ui.preselect == nil`. I think that this one portion of the `if` statement should be `config.ui.preselect ~= nil`.

This if statement only gives us a `vim.notify()` call, so the plugin functionality is not affected, but it is slightly annoying.

**Comment by andysazima** [comment]
Small correction: I think the logic checks are simply flipped. The notification suggests that we are looking for if the `config.ui.preselect_current` is set to false and the `config.ui.preselect` is not nil.

**Comment by leath-dub** [comment]
> Small correction: I think the logic checks are simply flipped. The notification suggests that we are looking for if the `config.ui.preselect_current` is set to false and the `config.ui.preselect` is not nil.

it is actually that I miss wrote the first one, it is that `config.ui.preselect_current` is set and `config.ui.preselect` is not nil as the conflict. I'll fix that now, very sorry again here.

**Comment by leath-dub** [comment]
This should be fixed now. Very sorry for the bugs lately, insomnia has be a bit sleep deprived lately.
