### ISSUE TITLE
FR: Setting function for sorting menu items

### ISSUE THREAD

**Issue by grimnight** [leath-dub/snipe.nvim#56]
Would it be possible to pass a sorter function to `menu:open` function?
This would help ensure that the entries are always in the order
that the programmer prefers.

The sorter function could by default be `table.sort`,
but it could be set to any sorter function.

Alternatively it could be a function that returns pairs.
For example `{{"w", "wrap"}, {"s", "spell"}}`.
This would allow using consistent and/or mnemonic keys.

<details>
  <summary>Small Snipe command</summary>

  Small Snipe command that I wrote.

  ```lua
  local function getTableKeys(tab)
    local keyset = {}
    for k,_ in pairs(tab) do
      keyset[#keyset + 1] = k
    end
    return keyset
  end

  local toggle_actions = {
    ["wrap"] = {
      state = function() return vim.o.wrap end,
      toggle = function() vim.o.wrap = not vim.o.wrap end
    },
    ["spell"] = {
      state = function() return vim.o.spell end,
      toggle = function() vim.o.spell = not vim.o.spell end
    },
  }
  local items = getTableKeys(toggle_actions)
  table.sort(items) -- This is currently needed to ensure consistency.

  local function snipe_toggle_stuff_menu()
  local Menu = require("snipe.menu")
  local menu = Menu:new({
    position = "cursor",
    open_win_override = { title = "Toggle" },
  })
  menu:add_new_buffer_callback(set_keymaps)
  menu:open(items, function(m, i)
    m:close()
    toggle_actions[m.items[i]].toggle()
  end, function (item)
    local state = toggle_actions[item].state() and "[X] " or "[ ] "
    return state .. item
  end)
  end
  vim.api.nvim_create_user_command("SnipeToggleStuff", snipe_toggle_stuff_menu, { nargs = 0 })
  ```

</details>

**Comment by leath-dub** [comment]
> Would it be possible to pass a sorter function to `menu:open` function? This would help ensure that the entries are always in the order that the programmer prefers.
> 
> The sorter function could by default be `table.sort`, but it could be set to any sorter function.
> 
> Alternatively it could be a function that returns pairs. For example `{{"w", "wrap"}, {"s", "spell"}}`. This would allow using consistent and/or mnemonic keys.
> Small Snipe command
> 
> Small Snipe command that I wrote.
> 
> ```lua
> local function getTableKeys(tab)
>   local keyset = {}
>   for k,_ in pairs(tab) do
>     keyset[#keyset + 1] = k
>   end
>   return keyset
> end
> 
> local toggle_actions = {
>   ["wrap"] = {
>     state = function() return vim.o.wrap end,
>     toggle = function() vim.o.wrap = not vim.o.wrap end
>   },
>   ["spell"] = {
>     state = function() return vim.o.spell end,
>     toggle = function() vim.o.spell = not vim.o.spell end
>   },
> }
> local items = getTableKeys(toggle_actions)
> table.sort(items) -- This is currently needed to ensure consistency.
> 
> local function snipe_toggle_stuff_menu()
> local Menu = require("snipe.menu")
> local menu = Menu:new({
>   position = "cursor",
>   open_win_override = { title = "Toggle" },
> })
> menu:add_new_buffer_callback(set_keymaps)
> menu:open(items, function(m, i)
>   m:close()
>   toggle_actions[m.items[i]].toggle()
> end, function (item)
>   local state = toggle_actions[item].state() and "[X] " or "[ ] "
>   return state .. item
> end)
> end
> vim.api.nvim_create_user_command("SnipeToggleStuff", snipe_toggle_stuff_menu, { nargs = 0 })
> ```

I dont think it makes sense to have a sort function on the menu, the reason the menu takes items everytime you open is so you have full control of the items. If you want to sort the items you can do that outside of the menu.

**Comment by leath-dub** [comment]
> Unfortunate, but seems reasonable. I decided to just use `items = { [1] = "wrap", [2] = "spell" }`, not necessarily ideal, but it is explicit.
> 
> I also experimented with changing `hints.dictionary`, but it doesn't seem to work. Even after setting it to `qwerty` it still shows hints `sa`.

Could you send me the exact config you are using that means `hints.dictionary` doesn't work, I can't reproduce this.

**Comment by leath-dub** [comment]
> I use lazy.nvim and this is the opts section:
> 
> ```
>     opts = {
>       ui = {
>         -- max_width = -1, -- -1 means dynamic width
>         max_height = -1, -- -1 means dynamic height
>         -- Where to place the ui window
>         -- Can be any of "topleft", "bottomleft", "topright", "bottomright", "center", "cursor" (sets under the current cursor pos)
>         position = "topleft",
>         -- Override options passed to `nvim_open_win`
>         -- Be careful with this as snipe will not validate
>         -- anything you override here. See `:h nvim_open_win`
>         -- for config options
>         open_win_override = {
>           -- title = "My Window Title",
>           border = "single", -- use "rounded" for rounded border
>         },
>         -- Preselect the currently open buffer
>         preselect_current = false,
> 
>         -- Set a function to preselect the currently open buffer
>         -- E.g, `preselect = require("snipe").preselect_by_classifier("#")` to
>         -- preselect alternate buffer (see :h ls and look at the "Indicators")
>         preselect = nil, -- function (bs: Buffer[] [see lua/snipe/buffer.lua]) -> int (index)
> 
>         -- Changes how the items are aligned: e.g. "<tag> foo    " vs "<tag>    foo"
>         -- Can be "left", "right" or "file-first"
>         -- NOTE: "file-first" buts the file name first and then the directory name
>         text_align = "file-first",
>       },
>       hints = {
>         -- Charaters to use for hints (NOTE: make sure they don't collide with the navigation keymaps)
>         -- dictionary = "sadflewcmpghio", -- default
>         -- dictionary = "sadfgqwertzxcvb",
>         -- dictionary = "wsadfgqertzxcvb",
>         dictionary = "qwerty",
>       },
>       navigate = {
>         -- When the list is too long it is split into pages
>         -- `[next|prev]_page` options allow you to navigate
>         -- this list
>         next_page = "J",
>         prev_page = "K",
> 
>         -- You can also just use normal navigation to go to the item you want
>         -- this option just sets the keybind for selecting the item under the
>         -- cursor
>         under_cursor = "<cr>",
> 
>         -- In case you changed your mind, provide a keybind that lets you
>         -- cancel the snipe and close the window.
>         cancel_snipe = "<esc>",
> 
>         -- Close the buffer under the cursor
>         -- Remove "j" and "k" from your dictionary to navigate easier to delete
>         -- NOTE: Make sure you don't use the character below in your dictionary
>         close_buffer = "D",
> 
>         -- Open buffer in vertical split
>         open_vsplit = "V",
> 
>         -- Open buffer in split, based on `vim.opt.splitbelow`
>         open_split = "H",
> 
>         -- Change tag manually
>         change_tag = "C",
>       },
>       -- Define the way buffers are sorted by default
>       -- Can be any of "default" (sort buffers by their number) or "last" (sort buffers by last accessed)
>       sort = "default",
>     }
> ```

do you also by any chance have a config function aswell ?

**Comment by leath-dub** [comment]
> Yes, I create my menu there, but I pass `opts` to the setup function.

Yeah the options you pass to snipe are only applied to the default menu. Every other menu just uses the default options unless you pass custom menu options. See here: https://github.com/leath-dub/snipe.nvim/blob/main/lua/snipe/menu.lua#L32

This is the default config and you can pass the same options into the menu when you call `:new`

**Comment by leath-dub** [comment]
> Yes, I create my menu there, but I pass `opts` to the setup function.

I cant reproduce this with what you have given me, can I see the whole config ?

**Comment by leath-dub** [comment]
> I tries passing the options to `Menu:new`, but it didn't work.
> My Snipe config
> 
> ```lua
> {
>   "leath-dub/snipe.nvim",
>   keys = { "gb", function() require("snipe").open_buffer_menu() end, desc = "Open Snipe buffer menu", },
>   cmd = { "SnipeToggleUiSelect", "SnipeToggleStuff" },
>   opts = {
>     ui = {
>       max_height = -1, -- -1 means dynamic height
>       -- Where to place the ui window
>       -- Can be any of "topleft", "bottomleft", "topright", "bottomright", "center", "cursor" (sets under the current cursor pos)
>       position = "topleft",
>       -- Override options passed to `nvim_open_win`
>       -- Be careful with this as snipe will not validate
>       -- anything you override here. See `:h nvim_open_win`
>       -- for config options
>       open_win_override = {
>         -- title = "My Window Title",
>         border = "single", -- use "rounded" for rounded border
>       },
>       -- Preselect the currently open buffer
>       -- preselect_current = true,
>       preselect_current = false,
> 
>       -- Set a function to preselect the currently open buffer
>       -- E.g, `preselect = require("snipe").preselect_by_classifier("#")` to
>       -- preselect alternate buffer (see :h ls and look at the "Indicators")
>       preselect = nil, -- function (bs: Buffer[] [see lua/snipe/buffer.lua]) -> int (index)
> 
>       -- Changes how the items are aligned: e.g. "<tag> foo    " vs "<tag>    foo"
>       -- Can be "left", "right" or "file-first"
>       -- NOTE: "file-first" buts the file name first and then the directory name
>       text_align = "file-first",
>     },
>     hints = {
>       -- Charaters to use for hints (NOTE: make sure they don't collide with the navigation keymaps)
>       -- dictionary = "sadflewcmpghio", -- default
>       -- dictionary = "sadfgqwertzxcvb",
>       -- dictionary = "wsadfgqertzxcvb",
>       dictionary = "qwerty",
>     },
>     navigate = {
>       -- When the list is too long it is split into pages
>       -- `[next|prev]_page` options allow you to navigate
>       -- this list
>       next_page = "J",
>       prev_page = "K",
> 
>       -- You can also just use normal navigation to go to the item you want
>       -- this option just sets the keybind for selecting the item under the
>       -- cursor
>       under_cursor = "<cr>",
> 
>       -- In case you changed your mind, provide a keybind that lets you
>       -- cancel the snipe and close the window.
>       cancel_snipe = "<esc>",
> 
>       -- Close the buffer under the cursor
>       -- Remove "j" and "k" from your dictionary to navigate easier to delete
>       -- NOTE: Make sure you don't use the character below in your dictionary
>       close_buffer = "D",
> 
>       -- Open buffer in vertical split
>       open_vsplit = "V",
> 
>       -- Open buffer in split, based on `vim.opt.splitbelow`
>       open_split = "H",
> 
>       -- Change tag manually
>       change_tag = "C",
>     },
>     -- Define the way buffers are sorted by default
>     -- Can be any of "default" (sort buffers by their number) or "last" (sort buffers by last accessed)
>     sort = "default",
>   },
>   config = function(_, opts)
>     local snipe = require("snipe")
> 
>     local function set_keymaps(m)
>       local nav_next = function()
>         m:goto_next_page()
>         m:reopen()
>       end
> 
>       local nav_prev = function()
>         m:goto_prev_page()
>         m:reopen()
>       end
> 
>       vim.keymap.set("n", "J", nav_next, { nowait = true, buffer = m.buf })
>       vim.keymap.set("n", "K", nav_prev, { nowait = true, buffer = m.buf })
>       vim.keymap.set("n", "<esc>", function()
>         m:close()
>       end, { nowait = true, buffer = m.buf })
>     end
> 
>     -- This makes vim.ui.select menus open in the center,
>     --      with <esc> to cancel.
>     snipe.ui_select_menu = require("snipe.menu"):new({ position = "center" })
>     snipe.ui_select_menu:add_new_buffer_callback(set_keymaps)
>     local snipe_old_ui_select = vim.ui.select
>     local snipe_ui_select_toggle = true
>     local snipe_ui_select_menu = function()
>       if snipe_ui_select_toggle then
>         vim.ui.select = snipe.ui_select
>         snipe_ui_select_toggle = false
>       else
>         vim.ui.select = snipe_old_ui_select
>         snipe_ui_select_toggle = true
>       end
>     end
>     cmd("SnipeToggleUiSelect", snipe_ui_select_menu, { desc = "Toggle using Snipe.nvim for ui.select" })
> 
>     local snipe_toggle_actions = require("config.snipe_toggle_actions")
>     local toggle_actions = snipe_toggle_actions.toggle_actions
>     local items = snipe_toggle_actions.items
> 
>     local function snipe_toggle_stuff_menu()
>       local Menu = require("snipe.menu")
>       local custom_config = {
>         position = "cursor",
>         open_win_override = { title = "Toggle" },
>         hints = {
>           -- dictionary = "sadflewcmpghio", -- default
>           -- dictionary = "sadfgqwertzxcvb",
>           -- dictionary = "wsadfgqertzxcvb",
>           dictionary = "qwerty",
>         },
>       }
>       local menu = Menu:new(custom_config)
>       menu:add_new_buffer_callback(set_keymaps)
>       menu:open(items, function(m, i)
>         local select = m.items[i]
>         m:close()
>         toggle_actions[select].toggle()
>       end, function (item)
>         local state = toggle_actions[item].state() and "[X] " or "[ ] "
>         return state .. item
>       end)
>     end
>     vim.api.nvim_create_user_command("SnipeToggleStuff", snipe_toggle_stuff_menu, { nargs = 0 })
> 
>     snipe.setup(opts)
>   end,
> },
> ```

ohhh, the menu config schema is different than the snipe config. You can look in the `menu.lua` file. The configs are different because the snipe config is just for the builtin buffer list and adds a bunch of extra stuff. The menu config is smaller and simpler, just what is needed for providing the basic menu interface.
