### ISSUE TITLE
Feature Request: Deleting a 'modified' buffer should ask for save before closing

### ISSUE THREAD

**Issue by davidsierradz** [leath-dub/snipe.nvim#59]
Maybe make it an option?

```diff
@ lua/snipe/init.lua:52 @ function Snipe.default_keymaps(m)
     -- window cannot be deleted when focused on a floating window
     m.opened_from_wid = m:open_over()
     vim.api.nvim_set_current_win(m.opened_from_wid)
-    vim.api.nvim_buf_delete(bufnr, { force = true })
+    vim.api.nvim_buf_delete(bufnr, { force = false })
     vim.api.nvim_set_current_win(m.win)
     table.remove(m.items, hovered)
     m:reopen()
```

I was not aware of `force = true` and accidentally lost some changes in a buffer

**Comment by leath-dub** [comment]
> Maybe make it an option?
> 
> ```diff
> @ lua/snipe/init.lua:52 @ function Snipe.default_keymaps(m)
>      -- window cannot be deleted when focused on a floating window
>      m.opened_from_wid = m:open_over()
>      vim.api.nvim_set_current_win(m.opened_from_wid)
> -    vim.api.nvim_buf_delete(bufnr, { force = true })
> +    vim.api.nvim_buf_delete(bufnr, { force = false })
>      vim.api.nvim_set_current_win(m.win)
>      table.remove(m.items, hovered)
>      m:reopen()
> ```
> 
> I was not aware of `force = true` and accidentally lost some changes in a buffer

I can change this now.

**Comment by leath-dub** [comment]
should be fixed now
