### ISSUE TITLE
Option to display only the file name in the snipe window. 

### ISSUE THREAD

**Issue by ShivamRawat0l** [leath-dub/snipe.nvim#60]
Use Case: 

If i want to navigate quickly through the buffers i want only to see the file name and navigate rather then seeing the whole file path

**Comment by leath-dub** [comment]
> Use Case:
> 
> If i want to navigate quickly through the buffers i want only to see the file name and navigate rather then seeing the whole file path

I think `ui.text_align` set to `"file-first"` is what you are looking for. This puts the file name first and the directory it is in on the right
