### ISSUE TITLE
attempt to index field 'options' (a nil value)

### ISSUE THREAD

**Issue by jemag** [leath-dub/snipe.nvim#64]
I am currenty getting this error intermittently:
![image](https://github.com/user-attachments/assets/6900a507-428c-4832-81f7-5e8f6f50fac9)
Unfortunately, I cannot create a 100% reproduction, as it does not seem to happen under every circumstances.

I have tried investigating the code, but I have been unable to tell why in some situations `options` might become nil, and work fine in others.

Configuration with Lazy is the one provided by README
```lua
  {
    "leath-dub/snipe.nvim",
    keys = {
      {
        "gb",
        function()
          require("snipe").open_buffer_menu()
        end,
        desc = "Open Snipe buffer menu",
      },
    },
    opts = {},
  },
```

The steps where the problem might show is usually:
1. Trigger buffer menu
2. Select buffer
3. Re-trigger buffer menu
4. Notice error

Or could happen instantly on the first triggering of the buffer menu

**Comment by leath-dub** [comment]
> I am currenty getting this error intermittently: ![image](https://private-user-images.githubusercontent.com/7985687/398008837-6900a507-428c-4832-81f7-5e8f6f50fac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MTkxODMsIm5iZiI6MTczNDkxODg4MywicGF0aCI6Ii83OTg1Njg3LzM5ODAwODgzNy02OTAwYTUwNy00MjhjLTQ4MzItODFmNy01ZThmNmY1MGZhYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjNUMDE1NDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjNmODgzMmY0ZDEzMWE5OTNmMzVmMDk4ZjFkYTJmYmNhNzBjMDI1MzY0MmRmZTgzYzg0YzdiZDU3NzgwNTViMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.I7mDwjBtKDJiUroSL23XgbnXpUui6yM17Ug-ZqmTN3U) Unfortunately, I cannot create a 100% reproduction, as it does not seem to happen under every circumstances.
> 
> I have tried investigating the code, but I have been unable to tell why in some situations `options` might become nil, and work fine in others.
> 
> Configuration with Lazy is the one provided by README
> 
> ```lua
>   {
>     "leath-dub/snipe.nvim",
>     keys = {
>       {
>         "gb",
>         function()
>           require("snipe").open_buffer_menu()
>         end,
>         desc = "Open Snipe buffer menu",
>       },
>     },
>     opts = {},
>   },
> ```
> 
> The steps where the problem might show is usually:
> 
> 1. Trigger buffer menu
> 2. Select buffer
> 3. Re-trigger buffer menu
> 4. Notice error
> 
> Or could happen instantly on the first triggering of the buffer menu

Thank you for raising this issue, I don't have it myself but it seems like a nasty one. I think I fixed it there though, I had `M` as a global in `config.lua` which is probably very problematic lol 😂.

Let me know if this fixes your issue, I'll leave this issue open for a bit.

**Comment by jemag** [comment]
oh wow, I hadn't noticed that, spent quite a bit of time trying to find the issue, I don't like writing issues without a good reproduction.

Thank you so much, I haven't been able to reproduce the issue so far since updating.
