### ISSUE TITLE
Remove `j` and `k` from the default hints dictionary

### ISSUE THREAD

**Issue by stefanlogue** [leath-dub/snipe.nvim#9]
Default hints should not use default navigation keys in Vim, as this inhibits the ability to navigate the list using those keys

**Comment by linkarzu** [comment]
- Agree, I set up my dictionary and remove them from there, but now that I think about it, why would you want to navigate using `j` and `k`, the purpose of the plugin is to open it, hit a key and get to that buffer, right?
- I use bufexplorer and I navigate with j and k, also my tmux sessions I navigate them with j and k
- But I'm not sure if I want to "navigate" in this plugin when it's purpose is to quickly get to a buffer
- Thoughts?

**Comment by leath-dub** [comment]
Yeah I planned to do this, ill fix this now
